import { StyleSheet } from "@react-pdf/renderer";
// La métrica nativa de las fuentes evita que el paginado dinámico de React PDF multiplique lineHeight al recalcular.
export const pdfStyles = StyleSheet.create({
  page: {
    padding: 42,
    paddingBottom: 70,
    fontSize: 9,
    color: "#244050",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottomWidth: 1.5,
    paddingBottom: 20,
  },
  business: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    maxWidth: "65%",
  },
  logo: { width: 42, height: 42, objectFit: "contain" },
  businessName: { fontSize: 16, fontWeight: 700 },
  muted: { color: "#607784", fontSize: 8 },
  label: {
    color: "#7a8b95",
    fontSize: 6.5,
    letterSpacing: 1,
    marginBottom: 5,
  },
  heading: { marginTop: 25, marginBottom: 23 },
  title: { fontSize: 17, fontWeight: 700 },
  parties: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  dates: { flexDirection: "row", gap: 24 },
  row: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#e2e9ee",
    paddingVertical: 12,
    paddingHorizontal: 6,
  },
  headRow: {
    paddingVertical: 9,
    backgroundColor: "#f3f7f8",
    fontSize: 8,
    fontWeight: 700,
  },
  description: { width: "48%", paddingRight: 12 },
  quantity: { width: "10%", textAlign: "right" },
  price: { width: "20%", textAlign: "right" },
  amount: { width: "22%", textAlign: "right" },
  itemMeta: { color: "#82939b", fontSize: 6.5, marginTop: 4 },
  bottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 22,
    marginBottom: 24,
    gap: 24,
  },
  notes: { width: "48%", paddingRight: 8 },
  totals: { width: "44%" },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
  },
  grand: {
    borderTopWidth: 0.7,
    borderTopColor: "#dae4e9",
    paddingTop: 10,
    marginTop: 6,
    alignItems: "center",
  },
  terms: {
    paddingTop: 12,
    marginBottom: 12,
  },
  footer: {
    height: 30,
    width: 511,
    position: "absolute",
    bottom: 27,
    left: 42,
    right: 42,
    borderTopWidth: 0.5,
    borderTopColor: "#e2e9ee",
    paddingTop: 4,
    flexDirection: "row",
    justifyContent: "space-between",
    color: "#607886",
    fontSize: 6.5,
  },
  bodyCopy: { fontSize: 8, color: "#71838c" },
});
