import type { TemplateDefinition, Plan } from "@/types/domain";
export { TEMPLATE_IDS } from "./template-ids";
/** Un perfil describe decisiones de composición; HTML y PDF consumen exactamente el mismo contrato. */
export const TEMPLATES: TemplateDefinition[] = [
  {
    id: "essential",
    name: "Esencial",
    plan: "free",
    description:
      "Identidad y folio en equilibrio, tabla con divisores y cierre alineado a la derecha.",
    defaultColor: "#06466f",
    defaultFont: "sans",
    layout: {
      header: "split",
      title: "plain",
      parties: "split",
      table: "line",
      totals: "right",
      frame: "none",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "clarity",
    name: "Claridad",
    plan: "free",
    description:
      "Identidad centrada, tabla de lectura abierta y cierre alineado a la derecha.",
    defaultColor: "#235449",
    defaultFont: "humanist",
    layout: {
      header: "center",
      title: "plain",
      parties: "line",
      table: "minimal",
      totals: "right",
      frame: "none",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "ledger",
    name: "Oficio",
    plan: "free",
    description:
      "Identidad y folio en equilibrio, retícula técnica y cierre en bloque definido.",
    defaultColor: "#334155",
    defaultFont: "mono",
    layout: {
      header: "split",
      title: "rule",
      parties: "split",
      table: "grid",
      totals: "box",
      frame: "top",
      density: "compact",
      headingFirst: false,
    },
  },
  {
    id: "linear",
    name: "Línea",
    plan: "free",
    description:
      "Folio protagonista y marca a la derecha, tabla con divisores y cierre alineado a la derecha.",
    defaultColor: "#274b66",
    defaultFont: "dm",
    layout: {
      header: "reverse",
      title: "plain",
      parties: "line",
      table: "line",
      totals: "right",
      frame: "none",
      density: "compact",
      headingFirst: false,
    },
  },
  {
    id: "balance",
    name: "Balance",
    plan: "free",
    description:
      "Identidad centrada, ritmo alterno entre conceptos y cierre alineado a la derecha.",
    defaultColor: "#2b5b59",
    defaultFont: "plex",
    layout: {
      header: "center",
      title: "rule",
      parties: "split",
      table: "zebra",
      totals: "right",
      frame: "none",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "origin",
    name: "Origen",
    plan: "free",
    description:
      "Identidad y folio en equilibrio, tabla de lectura abierta y cierre a la izquierda.",
    defaultColor: "#694235",
    defaultFont: "sans",
    layout: {
      header: "split",
      title: "plain",
      parties: "tint",
      table: "minimal",
      totals: "left",
      frame: "side",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "folio",
    name: "Folio",
    plan: "free",
    description:
      "Cabecera tipográfica de publicación, tabla con divisores y cierre alineado a la derecha.",
    defaultColor: "#34302d",
    defaultFont: "serif",
    layout: {
      header: "masthead",
      title: "plain",
      parties: "line",
      table: "line",
      totals: "right",
      frame: "none",
      density: "compact",
      headingFirst: true,
    },
  },
  {
    id: "norte",
    name: "Norte",
    plan: "free",
    description:
      "Identidad y folio en equilibrio, ritmo alterno entre conceptos y cierre en bloque definido.",
    defaultColor: "#365a72",
    defaultFont: "humanist",
    layout: {
      header: "split",
      title: "rule",
      parties: "stack",
      table: "zebra",
      totals: "box",
      frame: "none",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "base",
    name: "Base",
    plan: "free",
    description:
      "Folio protagonista y marca a la derecha, tabla con divisores y cierre a la izquierda.",
    defaultColor: "#395845",
    defaultFont: "plex",
    layout: {
      header: "reverse",
      title: "rule",
      parties: "tint",
      table: "line",
      totals: "left",
      frame: "none",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "pure",
    name: "Pura",
    plan: "free",
    description:
      "Identidad centrada, tabla de lectura abierta y cierre a la izquierda.",
    defaultColor: "#56516b",
    defaultFont: "dm",
    layout: {
      header: "center",
      title: "plain",
      parties: "stack",
      table: "minimal",
      totals: "left",
      frame: "top",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "grid",
    name: "Retícula",
    plan: "free",
    description:
      "Identidad y folio en equilibrio, retícula técnica y cierre alineado a la derecha.",
    defaultColor: "#3d4c58",
    defaultFont: "mono",
    layout: {
      header: "split",
      title: "panel",
      parties: "split",
      table: "grid",
      totals: "right",
      frame: "none",
      density: "compact",
      headingFirst: false,
    },
  },
  {
    id: "letter",
    name: "Carta",
    plan: "free",
    description:
      "Cabecera tipográfica de publicación, tabla de lectura abierta y cierre en bloque definido.",
    defaultColor: "#654538",
    defaultFont: "lora",
    layout: {
      header: "masthead",
      title: "rule",
      parties: "split",
      table: "minimal",
      totals: "box",
      frame: "side",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "studio",
    name: "Estudio",
    plan: "pro",
    description:
      "Cabecera de marca en contraste, tabla con divisores y cierre en una franja de color.",
    defaultColor: "#06466f",
    defaultFont: "sans",
    layout: {
      header: "band",
      title: "rule",
      parties: "tint",
      table: "line",
      totals: "band",
      frame: "none",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "frame",
    name: "Marco",
    plan: "pro",
    description:
      "Identidad y folio en equilibrio, tabla con divisores y cierre en bloque definido.",
    defaultColor: "#734056",
    defaultFont: "humanist",
    layout: {
      header: "split",
      title: "panel",
      parties: "stack",
      table: "line",
      totals: "box",
      frame: "border",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "horizon",
    name: "Horizonte",
    plan: "pro",
    description:
      "Folio protagonista y marca a la derecha, encabezado de tabla en tinta y cierre en una franja de color.",
    defaultColor: "#8a4b2b",
    defaultFont: "dm",
    layout: {
      header: "reverse",
      title: "rule",
      parties: "split",
      table: "ink",
      totals: "band",
      frame: "top",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "axis",
    name: "Eje",
    plan: "pro",
    description:
      "Identidad lateral y composición asimétrica, ritmo alterno entre conceptos y cierre alineado a la derecha.",
    defaultColor: "#125b56",
    defaultFont: "plex",
    layout: {
      header: "rail",
      title: "plain",
      parties: "split",
      table: "zebra",
      totals: "right",
      frame: "side",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "duo",
    name: "Dúo",
    plan: "pro",
    description:
      "Cabecera de marca en contraste, tabla de lectura abierta y cierre a la izquierda.",
    defaultColor: "#3b5078",
    defaultFont: "dm",
    layout: {
      header: "band",
      title: "panel",
      parties: "line",
      table: "minimal",
      totals: "left",
      frame: "none",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "module",
    name: "Módulo",
    plan: "pro",
    description:
      "Folio protagonista y marca a la derecha, retícula técnica y cierre en bloque definido.",
    defaultColor: "#334155",
    defaultFont: "mono",
    layout: {
      header: "reverse",
      title: "panel",
      parties: "tint",
      table: "grid",
      totals: "box",
      frame: "border",
      density: "compact",
      headingFirst: false,
    },
  },
  {
    id: "contour",
    name: "Contorno",
    plan: "pro",
    description:
      "Identidad centrada, encabezado de tabla en tinta y cierre alineado a la derecha.",
    defaultColor: "#49633b",
    defaultFont: "lora",
    layout: {
      header: "center",
      title: "rule",
      parties: "stack",
      table: "ink",
      totals: "right",
      frame: "border",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "signal",
    name: "Señal",
    plan: "pro",
    description:
      "Cabecera de marca en contraste, tabla con divisores y cierre en bloque definido.",
    defaultColor: "#913b46",
    defaultFont: "sans",
    layout: {
      header: "band",
      title: "large",
      parties: "split",
      table: "line",
      totals: "box",
      frame: "side",
      density: "compact",
      headingFirst: true,
    },
  },
  {
    id: "prisma",
    name: "Prisma",
    plan: "pro",
    description:
      "Identidad lateral y composición asimétrica, encabezado de tabla en tinta y cierre a la izquierda.",
    defaultColor: "#4f467c",
    defaultFont: "humanist",
    layout: {
      header: "rail",
      title: "rule",
      parties: "tint",
      table: "ink",
      totals: "left",
      frame: "none",
      density: "normal",
      headingFirst: false,
    },
  },
  {
    id: "format",
    name: "Formato",
    plan: "pro",
    description:
      "Cabecera tipográfica de publicación, retícula técnica y cierre en una franja de color.",
    defaultColor: "#2a535e",
    defaultFont: "plex",
    layout: {
      header: "masthead",
      title: "panel",
      parties: "line",
      table: "grid",
      totals: "band",
      frame: "top",
      density: "compact",
      headingFirst: false,
    },
  },
  {
    id: "focus",
    name: "Enfoque",
    plan: "pro",
    description:
      "Folio protagonista y marca a la derecha, tabla de lectura abierta y cierre en bloque definido.",
    defaultColor: "#684438",
    defaultFont: "dm",
    layout: {
      header: "reverse",
      title: "large",
      parties: "stack",
      table: "minimal",
      totals: "box",
      frame: "side",
      density: "normal",
      headingFirst: true,
    },
  },
  {
    id: "urban",
    name: "Urbana",
    plan: "pro",
    description:
      "Identidad lateral y composición asimétrica, ritmo alterno entre conceptos y cierre en una franja de color.",
    defaultColor: "#2e4a60",
    defaultFont: "sans",
    layout: {
      header: "rail",
      title: "panel",
      parties: "line",
      table: "zebra",
      totals: "band",
      frame: "border",
      density: "compact",
      headingFirst: false,
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    plan: "premium",
    description:
      "Identidad y folio en equilibrio, tabla de lectura abierta y cierre alineado a la derecha.",
    defaultColor: "#173f38",
    defaultFont: "serif",
    layout: {
      header: "split",
      title: "large",
      parties: "line",
      table: "minimal",
      totals: "right",
      frame: "top",
      density: "airy",
      headingFirst: true,
    },
  },
  {
    id: "signature",
    name: "Firma",
    plan: "premium",
    description:
      "Identidad lateral y composición asimétrica, tabla de lectura abierta y cierre a la izquierda.",
    defaultColor: "#292844",
    defaultFont: "lora",
    layout: {
      header: "rail",
      title: "large",
      parties: "stack",
      table: "minimal",
      totals: "left",
      frame: "side",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "atelier",
    name: "Atelier",
    plan: "premium",
    description:
      "Cabecera tipográfica de publicación, ritmo alterno entre conceptos y cierre en bloque definido.",
    defaultColor: "#4e3b2e",
    defaultFont: "baskerville",
    layout: {
      header: "masthead",
      title: "large",
      parties: "line",
      table: "zebra",
      totals: "box",
      frame: "none",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "archive",
    name: "Archivo",
    plan: "premium",
    description:
      "Folio protagonista y marca a la derecha, retícula técnica y cierre en una franja de color.",
    defaultColor: "#334b4f",
    defaultFont: "plex",
    layout: {
      header: "reverse",
      title: "large",
      parties: "tint",
      table: "grid",
      totals: "band",
      frame: "border",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "monograph",
    name: "Monografía",
    plan: "premium",
    description:
      "Identidad lateral y composición asimétrica, encabezado de tabla en tinta y cierre alineado a la derecha.",
    defaultColor: "#3c4f45",
    defaultFont: "baskerville",
    layout: {
      header: "rail",
      title: "large",
      parties: "line",
      table: "ink",
      totals: "right",
      frame: "none",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "aura",
    name: "Aura",
    plan: "premium",
    description:
      "Identidad centrada, tabla de lectura abierta y cierre en una franja de color.",
    defaultColor: "#725a25",
    defaultFont: "lora",
    layout: {
      header: "center",
      title: "large",
      parties: "tint",
      table: "minimal",
      totals: "band",
      frame: "side",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "capital",
    name: "Capital",
    plan: "premium",
    description:
      "Cabecera de marca en contraste, retícula técnica y cierre en bloque definido.",
    defaultColor: "#252e49",
    defaultFont: "serif",
    layout: {
      header: "band",
      title: "large",
      parties: "line",
      table: "grid",
      totals: "box",
      frame: "top",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "gallery",
    name: "Galería",
    plan: "premium",
    description:
      "Cabecera tipográfica de publicación, tabla de lectura abierta y cierre a la izquierda.",
    defaultColor: "#653f54",
    defaultFont: "dm",
    layout: {
      header: "masthead",
      title: "panel",
      parties: "stack",
      table: "minimal",
      totals: "left",
      frame: "border",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "volume",
    name: "Volumen",
    plan: "premium",
    description:
      "Identidad lateral y composición asimétrica, tabla con divisores y cierre en bloque definido.",
    defaultColor: "#80523b",
    defaultFont: "lora",
    layout: {
      header: "rail",
      title: "panel",
      parties: "tint",
      table: "line",
      totals: "box",
      frame: "top",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "manifest",
    name: "Manifiesto",
    plan: "premium",
    description:
      "Folio protagonista y marca a la derecha, encabezado de tabla en tinta y cierre a la izquierda.",
    defaultColor: "#173f4d",
    defaultFont: "sans",
    layout: {
      header: "reverse",
      title: "large",
      parties: "line",
      table: "ink",
      totals: "left",
      frame: "none",
      density: "airy",
      headingFirst: true,
    },
  },
  {
    id: "heritage",
    name: "Legado",
    plan: "premium",
    description:
      "Cabecera tipográfica de publicación, tabla de lectura abierta y cierre en una franja de color.",
    defaultColor: "#4d5637",
    defaultFont: "baskerville",
    layout: {
      header: "masthead",
      title: "rule",
      parties: "tint",
      table: "minimal",
      totals: "band",
      frame: "border",
      density: "airy",
      headingFirst: false,
    },
  },
  {
    id: "edition",
    name: "Edición",
    plan: "premium",
    description:
      "Identidad centrada, tabla con divisores y cierre en bloque definido.",
    defaultColor: "#513d35",
    defaultFont: "serif",
    layout: {
      header: "center",
      title: "large",
      parties: "stack",
      table: "line",
      totals: "box",
      frame: "top",
      density: "airy",
      headingFirst: true,
    },
  },
];
export function templateById(id: string): TemplateDefinition {
  return TEMPLATES.find((entry) => entry.id === id) ?? TEMPLATES[0];
}
export function filterTemplates(plan: string = "all") {
  return TEMPLATES.filter((entry) => plan === "all" || entry.plan === plan);
}
export function templateCount(plan: Plan | "all" = "all") {
  return filterTemplates(plan).length;
}
